- docs/.vuepress/nav/zh.js
- docs/.vuepress/theme/components/NavLink.vue
> feat: :sparkles: add official site link in navigation bar

- dice.yml
> Update dice.yml, extended memory

- docs/1.0/manual/deploy/pipeline.md
> add if and cache action docs

- docs/.vuepress/sidebar/zh.js
> delete install document for not updated yet

- docs/1.0/manual/cli/explain-args.md
Update erda cli upload oss bucket
> Update erda cli doc

- docs/1.2/manual/faq/install.md
- package-lock.json
add faq about nfs and public kubernetes version
please review: @Dreamica @luobily
> feature: add faq about nfs and public kubernetes version

- docs/1.0/manual/install/docker-install.md
- docs/1.2/manual/install/docker-install.md
update quick-start url, use oss to speed up the installation
> update quick-start url

- docs/1.2/manual/install/helm-install/helm-install-demo.md
- docs/1.2/manual/install/helm-install/helm-install-prod.md
- docs/1.2/manual/quick-start/newbie.md
1. fix newbie.md link error
2. optimize install and configuration
Please review: @luobily @Dreamica
> fix: newbie.md link error

- docs/1.2/manual/dop/guides/reference/pipeline.md
add new pipeline expression syntax
> add pipeline placeholder syntax

- docs/1.2/manual/dop/guides/reference/pipeline.md
[erda link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=223195&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMDUiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=-1&type=TASK)
> pipeline expression grammar

- docs/1.2/manual/dop/guides/reference/pipeline.md
use <code v-pre> </code> instead of ```
> use <code v-pre> </code> instead of ```

- docs/1.2/manual/install/docker-install.md
- docs/1.3/manual/install/docker-install.md
feature: add faq for host-gateway error
> feature: add faq for host-gateway error

- docs/1.2/manual/eco-tools/kubeprober/guides/introduction.md
Adjust doc style
please review: @huangzx618
> Update kubeprober introduction

- docs/.vuepress/sidebar/zh.js
- docs/1.3/manual/dop/best-practices/api-drive-develop.md
Add best practice(api-drive-develop) in DOP
> Add api-drive-develop

- docs/1.2/manual/deploy/pipeline.md
- docs/1.2/manual/dop/guides/reference/pipeline.md
add comments to if configuration
> add comments to if configuration

- docs/1.2/manual/deploy/pipeline.md
- docs/1.2/manual/dop/guides/reference/pipeline.md
fix pipeline expression grammar issue
> Feature: fix pipeline expression grammar issue

- package.json
Files is too many now, memory is not enough for build script to run.
> chore: build need more memory

- docs/1.3/manual/faq/install.md
[erda issue link](https://erda.cloud/erda/dop/projects/387/issues/all?id=219016&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiOTIiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=467&type=TASK)
screenshot:
> faq for install: add mysql issue when docker-compose

- docs/.vuepress/enhanceApp.js
- docs/.vuepress/styles/index.styl
- docs/.vuepress/theme/layouts/Layout.vue
- package-lock.json
- package.json
This pr fix notification not show in production mode. Replace with another component.
> fix: notification not show in production mode

- docs/1.3/manual/install/helm-install/upgrade.md
- docs/1.3/manual/quick-start/newbie.md
Update newbie.md in quick start
> Feature: quick start doc modification

- docs/.vuepress/theme/components/SideAnchor.vue
Add some vertical space to anchor item.
> feat: add vertical space in fixed anchor item

- docs/1.3/manual/faq/install.md
- docs/1.3/manual/install/helm-install/configuration.md
- docs/1.4/manual/faq/install.md
- docs/1.4/manual/install/helm-install/configuration.md
1. fix: vitstor config about domain.
2. add faq: ingressClass error.
3. add faq: create org error when visit erda first.
change version: 1.3, 1.4
please review: @luobily @Dreamica
> faeture: add ingress and error faq.

- docs/1.3/manual/faq/install.md
- docs/1.4/manual/faq/install.md
Provides access to erda 504 error resolution document when deploying Docker Compose
> Provides access to erda 504 error resolution document when deploying Docker Compose

- docs/.vuepress/sidebar/vers/1.4.js
- docs/1.4/manual/dop/guides/qa-and-testing/e2e-code-coverage.md
> sourcecov docs

- docs/1.4/manual/install/helm-install/upgrade.md
> feature: add upgrade to 1.4.0

- docs/1.4/manual/cli/explain-args.md
更新 erda-cli-1.4 的文档
/assign @Dreamica
> update manual for cli

- docs/.vuepress/config.js
- docs/.vuepress/nav/en.js
- docs/.vuepress/nav/zh.js
- docs/.vuepress/sidebar/en.js
- docs/.vuepress/sidebar/zh.js
- docs/.vuepress/util.js
- docs/en/README.md
- docs/en/changeLog.md
- docs/en/faq.md
Support English version doc.
To prevent the build memory overflow, only the last two versions can be viewed.
> feat: support english version doc

- docs/1.3/manual/dop/examples/deploy/nexus.md
- docs/1.3/manual/dop/guides/reference/pipeline.md
- docs/1.4/manual/dop/examples/deploy/nexus.md
- docs/1.4/manual/dop/guides/reference/pipeline.md
> update pipeline express docs

- docs/.vuepress/sidebar/en.js
- docs/.vuepress/sidebar/vers/1.3-en.js
- docs/.vuepress/sidebar/vers/1.4-en.js
Add english version menu config file in `sidebar/vers/` folder.
You can update `-en` suffix file at your own.
> feat: add english version sidebar menu

- docs/1.5/manual/dop/guides/api/api-design.md
how to refer database structure fields in API Designing
> how to refer database structure fields in API Designing

- docs/1.5/manual/dop/guides/reference/pipeline.md
[Erda Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=267100&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyI5MiJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=TASK)
> feature: add doc for action meta

- docs/.vuepress/sidebar/vers/1.5.js
- docs/1.5/manual/dop/guides/collaboration/issue-gantt-chart.md
> Issue gantt chart manual

- pipeline.yml
refine pipeline separate out deploy step
> ci: refine pipeline separate out deploy step

- docs/.vuepress/sidebar/vers/1.6.js
- docs/1.6/manual/dop/best-practices/release.md
> feat: add deploy at best practices

- docs/1.6/manual/dop/examples/deploy/deploy-from-java-build.md
[erda link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJhc3NpZ25lZSI6WyIxMDAxMjA1Il19&id=287522&iterationID=1115&pId=0&type=TASK)
> fix: add tips for java-build

- docs/1.5/manual/cli/explain-args.md
- docs/en/1.5/manual/cli/explain-args.md
> update cli version for 1.5 doc

- docs/1.6/manual/cli/explain-args.md
- docs/en/1.6/manual/cli/explain-args.md
> update cli version for 1.6

- docs/1.6/manual/dop/guides/reference/pipeline.md
- package-lock.json
> feat: custom datetime format

- docs/2.0/manual/dop/guides/reference/pipeline.md
> feat: remove {{}}

- docs/2.0/manual/install/docker-install.md
feat: add docs for quick start installation
> feat: add docs for quick start installation

- docs/2.0/manual/faq/faq.md
> feat: add faq, how to setting custom maven repo

- docs/1.5/manual/dop/examples/deploy/nexus.md
- docs/1.5/manual/dop/guides/language/java.md
- docs/2.0/manual/dop/examples/deploy/nexus.md
- docs/2.0/manual/dop/guides/language/java.md
- docs/en/1.5/manual/dop/examples/deploy/nexus.md
- docs/en/1.5/manual/dop/guides/language/java.md
- docs/en/2.0/manual/dop/examples/deploy/nexus.md
- docs/en/2.0/manual/dop/guides/language/java.md
- docs/en/next/manual/dop/examples/deploy/nexus.md
- docs/en/next/manual/dop/guides/language/java.md
- docs/next/manual/dop/examples/deploy/nexus.md
- docs/next/manual/dop/guides/language/java.md
> update java build docs

- docs/next/manual/cli/explain-args.md
- docs/next/manual/cli/install.md
- docs/next/manual/cli/use.md
> update cli-2.1 doc

- docs/next/manual/cli/install.md
> update doc for cli 2.1

- docs/next/manual/dop/guides/qa-and-testing/deploy-sonarqube.md
add doc for how to deploy a sonarqub server
> add deploy sonarqube doc

- docs/next/manual/dop/guides/deploy/deploy-order.md
- docs/next/manual/dop/guides/deploy/release.md
> doc: release deploy modes

- .github/workflows/git-sync.yml
- pipeline.yml
auto deploy to TEST when master branch updated
> ci: auto deploy to TEST when master branch updated

- pipeline.yml
> ci: fix typo

- README.md
- docs/.vuepress/components/VideoPlayer.vue
- docs/.vuepress/enhanceApp.js
- docs/2.0/manual/about/intro.md
- package-lock.json
- package.json
> feat: support embed video

- docs/.vuepress/config.js
- docs/.vuepress/searchHooks.js
- docs/.vuepress/theme/components/Navbar.vue
> Fix: search result order

- docs/next/manual/msp/guides/apigw/policy.md
> feat: sbac doc

- docs/next/manual/install/helm-install/helm-install-demo.md
- docs/next/manual/install/helm-install/helm-install-prod.md
- docs/next/manual/install/helm-install/premise.md
> feat: erda 2.2.0 helm install docs

- docs/next/manual/install/helm-install/premise.md
> feat: update erda helm install docs

- docs/next/manual/dop/guides/deploy/management.md
增加 水平自动扩缩容操作说明
/assign reviewers @sixther-dc @huangzx618
> feat: add service horizontal pod autoscaler

- docs/next/manual/dop/guides/reference/dice-yaml.md
> feat: add k8s snippet dice yaml intor

- docs/2.1/manual/dop/guides/language/java.md
feature: Optimize the content of java arthas
> feature: Optimize the content of java arthas

- docs/next/manual/install/docker-install.md
- docs/next/manual/install/helm-install/introduction.md
add build source in install docs @huangzx618 
related pr: [5356](https://github.com/erda-project/erda/pull/5356)
> feat: add build source in install docs

- docs/next/manual/faq/faq.md
Add  FAQ for Erda Hepa Gateway rate limit.
> gateway_rate_limit

- docs/next/manual/faq/faq.md
> fix: adjust something

- docs/next/manual/msp/guides/apigw/auth.md
- docs/next/manual/msp/guides/apigw/mse_auth.md
本文档补充 Hepa 集成 MSE 网关之后，对应的网关认证授权方面的内容.
> feat: mse gateway auth

- archive/1.2/manual/faq/install.md
- archive/1.3/manual/faq/install.md
- archive/1.4/manual/faq/install.md
- archive/1.5/manual/faq/install.md
- archive/en/1.5/manual/faq/install.md
- docs/2.0/manual/faq/install.md
- docs/2.1/manual/faq/install.md
- docs/2.2/manual/faq/install.md
- docs/en/2.0/manual/faq/install.md
- docs/en/2.1/manual/faq/install.md
- docs/en/2.2/manual/faq/install.md
- docs/en/next/manual/faq/install.md
- docs/next/manual/faq/install.md
fix faq smtp env configuration error
> fix: faq smtp env configuration error

- docs/next/manual/msp/guides/apigw/mse_auth.md
Due to changes for  mse custom plugins configurations, need adjust mse para-sign-auth doc, and added infos about how to upload custom plugin
> fix: adjust mse para-sign-auth doc

- docs/.vuepress/sidebar/vers/2.2.js
- docs/2.2/manual/msp/guides/profile/overview.md
- docs/2.2/manual/msp/practice/profile/profile-cpu.md
- docs/2.2/manual/msp/practice/profile/profile-memory.md
> feat: 增加持续分析部分

- docs/next/manual/msp/guides/apigw/mse_policy.md
Add document about how to use and set gateway policy when use MSE Gateway in Erda。
> feat: support mse gateway policy

- docs/next/manual/msp/guides/apm/profile.md
> fix: mis path

- docs/next/manual/dop/guides/reference/pipeline.md
1. add a demo
2. add tip for compare
3. add implementation link
[related erda issue](https://erda.cloud/erda/dop/projects/387/issues/all?id=608319&iterationID=-1&type=TASK)
> add detail for pipeline.yml if expression

- docs/2.4/manual/dop/guides/reference/dice-yaml.md
- docs/en/next/manual/dop/guides/reference/dice-yaml.md
- docs/next/manual/dop/guides/reference/dice-yaml.md
add dice yaml environments description and example
@iutx 
https://erda.cloud/erda/dop/projects/387/issues/all?id=608199&iterationID=12783&type=TASK
> feat: add dice yaml environments description and example
